using Content.Client.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using TerraFX.Interop.Xlib;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MessengerMessageEntry : CartridgeButton
{
    public MessengerMessageEntry(SpriteSpecifier avatarIcon, string message, TimeSpan messageTime, bool ourMessage)
    {
        RobustXamlLoader.Load(this);
        AvatarIcon.SetFromSpriteSpecifier(avatarIcon);
        AvatarIcon.DisplayRect.Stretch = TextureRect.StretchMode.Scale;
        Message.SetMessage(FormattedMessage.FromUnformatted(message));
        TimeLabel.SetMessage(FormattedMessage.FromMarkup(messageTime.ToString("hh\\:mm")));
        TimeLabel.ToolTip = messageTime.ToString("dddd\\:hh\\:mm\\:ss");
        TimeLabel.MouseFilter = MouseFilterMode.Pass;

        if (ourMessage)
        {
            AvatarIconContainer.SetPositionLast();
            AvatarMessageSeparator.SetPositionFirst();
            HorizontalAlignment = HAlignment.Right;
        }
    }
}
