using Content.Client.PDA;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MessengerContactEntry : CartridgeButton
{
    public MessengerContactEntry(string userName, SpriteSpecifier avatarIcon, string lastMessage)
    {
        RobustXamlLoader.Load(this);
        AvatarIcon.SetFromSpriteSpecifier(avatarIcon);
        AvatarIcon.DisplayRect.Stretch = TextureRect.StretchMode.Scale;
        UserName.Text = userName;

        var formattedLastMessage = FormattedMessage.FromMarkup(Loc.GetString("messenger-message-preview", ("message", $"{lastMessage}")));
        if (lastMessage.Length >= SharedMessengerSystem.MessagePreviewLimit)
        {
            formattedLastMessage = FormattedMessage.FromMarkup(Loc.GetString("messenger-message-preview",
                ("message", $"{lastMessage[..SharedMessengerSystem.MessagePreviewLimit]}...")));
        }
        MessagePreview.SetMessage(formattedLastMessage);
    }
}
