using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Onboarding.Controls;

[GenerateTypedNameReferences]
public sealed partial class OnboardingPopup : Popup
{
    public OnboardingPopup()
    {
        RobustXamlLoader.Load(this);

        CloseOnClick = false;

        Message.SetMessage(FormattedMessage.FromMarkupPermissive("AAAAAAAAAAAAAAAAAAAAAAAa"));
        CloseButton.OnPressed += _ => Close();
        EntriesCount.SetMessage(FormattedMessage.FromMarkupPermissive("1/4"));
    }
}
