using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Onboarding.Controls;

[GenerateTypedNameReferences]
public sealed partial class OnboardingPopup : PanelContainer
{
    private Queue<string> Entries = new();

    public OnboardingPopup()
    {
        RobustXamlLoader.Load(this);

        Message.SetMessage(FormattedMessage.FromMarkupPermissive("AAAAAAAAAAAAAAAAAAAAAAAa"));
        NextButton.OnPressed += _ =>
        {
            Dispose();
        };
        EntriesCount.SetMessage(FormattedMessage.FromMarkupPermissive("1/4"));
    }
}
