using Content.Shared.Onboarding;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Onboarding.Controls;

[GenerateTypedNameReferences]
public sealed partial class OnboardingSelector : BoxContainer
{
    private Dictionary<int, ProtoId<OnboardingCategoryPrototype>> _containedCategories = new();

    public OnboardingSelector()
    {
        RobustXamlLoader.Load(this);
        var controller = UserInterfaceManager.GetUIController<OnboardingUIController>();
        var protos = controller.GetOnboardingCategoryPrototypes();
        for (var i = 0; i < protos.Count; i++)
        {
            var proto = protos[i];
            Categories.AddItem(proto.Data.Name, i);
            _containedCategories.Add(i, proto);
        }

        Categories.OnItemSelected += args =>
        {
            Categories.SelectId(args.Id);
            ConfirmButton.Disabled = false;
        };
        ConfirmButton.OnPressed += _ =>
        {
            var selectedDifficulty = _containedCategories[Categories.SelectedId];
            ConfirmButton.Disabled = true;
            controller.ChangeConfiguration(selectedDifficulty);
        };
    }
}
